server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server-demo1
  cloud:
    config:
      label: master #git分支名称
      server:
        git:
          uri: https://github.com/liqihua/spring-cloud-config-file-demo1.git #git地址
          #username:
          #password:

